version: "3.7"

services:
  fastuiintro:
    container_name: fastuiintro
    hostname: fastuiintro.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    ports:
      - 1800:8000
    command: >
      bash -c "sleep infinity"
    networks:
      fastuiintro-net:

networks:
  fastuiintro-net:
